# Generated by Django 2.2 on 2020-08-19 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_api', '0001_initial'),
        ('users', '0002_auto_20200714_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='subscription',
        ),
        migrations.AddField(
            model_name='customuser',
            name='paid_until',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stripe_api.Plans'),
        ),
    ]
