# Generated by Django 2.2 on 2020-08-19 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200819_0538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='plan',
        ),
    ]
