# Generated by Django 2.2 on 2020-08-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200819_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stripe_cust_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stripe_email',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
