# Generated by Django 2.2 on 2020-08-22 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_api', '0006_plan_days_duration'),
        ('users', '0007_auto_20200820_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='plan_current_checkout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_current_checkout', to='stripe_api.Plan'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='stripe_api.Plan'),
        ),
    ]
