# Generated by Django 2.2 on 2020-08-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200822_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
