# Generated by Django 2.2 on 2020-08-22 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200822_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='paid_until',
            new_name='plan_paid_until',
        ),
    ]
