# Generated by Django 2.2 on 2020-08-22 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_api', '0008_auto_20200822_1752'),
        ('users', '0010_auto_20200822_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='one_time_current_checkout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stripe_products_current_checkout', to='stripe_api.OneTimeProduct'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='one_time_paid_until',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='one_time_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stripe_products', to='stripe_api.OneTimeProduct'),
        ),
    ]
