# Generated by Django 2.2 on 2020-08-24 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200822_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='one_time_current_checkout',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='one_time_paid_until',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='one_time_product',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='plan_current_checkout',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='plan_paid_until',
        ),
    ]
