# Generated by Django 2.2 on 2020-08-19 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_api', '0002_auto_20200819_1138'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plans',
            new_name='Plan',
        ),
    ]
