# Generated by Django 2.2 on 2020-08-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_api', '0004_auto_20200819_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='days_step',
            field=models.SmallIntegerField(default=3),
        ),
    ]
