# Generated by Django 2.2 on 2020-08-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_api', '0005_auto_20200819_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='days_duration',
            field=models.SmallIntegerField(null=True),
        ),
    ]
