# Generated by Django 2.2 on 2020-08-22 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200822_1744'),
        ('stripe_api', '0007_auto_20200822_1744'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='OneTimeProduct',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
