# Generated by Django 2.2 on 2020-08-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_api', '0008_auto_20200822_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimeproduct',
            name='days_duration',
        ),
        migrations.AddField(
            model_name='onetimeproduct',
            name='period',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='period',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
