# Generated by Django 2.2 on 2020-08-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_api', '0009_auto_20200823_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimeproduct',
            name='period',
            field=models.CharField(default='month', max_length=16),
        ),
        migrations.AlterField(
            model_name='plan',
            name='period',
            field=models.CharField(default='month', max_length=16),
        ),
    ]
