# Generated by Django 2.2 on 2020-08-24 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_api', '0010_auto_20200823_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(blank=True, max_length=64, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('collection_method', models.CharField(blank=True, max_length=32, null=True)),
                ('created', models.DateTimeField()),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('default_payment_method', models.CharField(blank=True, max_length=64, null=True)),
                ('price_id', models.CharField(blank=True, max_length=64, null=True)),
                ('product_id', models.CharField(blank=True, max_length=64, null=True)),
                ('url', models.CharField(blank=True, max_length=256, null=True)),
                ('latest_invoice', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='onetimeproduct',
            old_name='period',
            new_name='interval',
        ),
        migrations.RenameField(
            model_name='onetimeproduct',
            old_name='stripe_price_id',
            new_name='price_id',
        ),
        migrations.RenameField(
            model_name='onetimeproduct',
            old_name='stripe_product_id',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='period',
            new_name='interval',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='stripe_plan_id',
            new_name='plan_id',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='stripe_price_id',
            new_name='price_id',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='stripe_product_id',
            new_name='product_id',
        ),
        migrations.AddField(
            model_name='onetimeproduct',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='onetimeproduct',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='currency',
            field=models.CharField(default='eur', max_length=64),
        ),
        migrations.AddField(
            model_name='plan',
            name='interval_count',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='plan',
            name='trial_period_days',
            field=models.SmallIntegerField(default=0),
        ),
    ]
