# Generated by Django 2.2 on 2020-07-09 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(default='', max_length=32)),
                ('code', models.CharField(max_length=64)),
                ('marketplace', models.CharField(default='IT', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32)),
                ('platform', models.CharField(max_length=32)),
                ('other', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(default='', max_length=32)),
                ('code', models.CharField(max_length=64)),
                ('marketplace', models.CharField(default='IT', max_length=2)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='analyze.ProductParent')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyze.Seller')),
            ],
        ),
    ]
