# Generated by Django 2.2 on 2020-07-09 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0002_auto_20200709_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='productparent',
            name='seller',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='analyze.Seller'),
            preserve_default=False,
        ),
    ]
