# Generated by Django 2.2 on 2020-07-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0003_productparent_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='other',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='platform',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
