# Generated by Django 2.2 on 2020-08-11 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0008_amazonrank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amazonrank',
            old_name='pos_in_age',
            new_name='pos_in_page',
        ),
    ]
