# Generated by Django 2.2 on 2020-08-12 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0009_auto_20200811_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonrank',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analyze.Product'),
        ),
    ]
